### PR TITLE
Fixes existing warnings and notes from R CMD check

### PR DESCRIPTION
**Pull request by atheriel**
This is a minor change fixing some cosmetic issues:

- A NOTE about the title ending in a period.
- A NOTE about the namespace of the 'setNames' function.
- A WARNING about mismatched quotes in the documentation.

`R CMD check` now reports a clean bill of health.

@krlmlr I mentioned on Twitter that I'm interesting in taking on maintainership of this package. How would you like that to work?

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks Aaron.

@johnmyleswhite: Are you okay with me handing maintainership to Aaron, who'd like to add more features?

**Comment by johnmyleswhite** [comment]
Yes, turning over ownership is good by me. Thanks.

**Comment by krlmlr** [comment]
Thanks. Could you please invite Aaron to the repo? Aaron: you should be able to merge and edit after accepting the invitation.

**Comment by johnmyleswhite** [comment]
Invite sent

**Comment by atheriel** [comment]
Thanks!

**Pull request merged**
